### ISSUE TITLE
Access Dataset

### ISSUE THREAD

**Issue by teengineer** [SEU-zhc/complexPavementCrackDataset#1]
Hello, i cant access dataset this link [https://pan.baidu.com/s/1BdNnLYwtCcZYkr0ygai7Eg](https://pan.baidu.com/s/1BdNnLYwtCcZYkr0ygai7Eg). Can you help me?

**Comment by SEU-zhc** [comment]
Check your network, I can access it smoothly, but you might need a VPN.

**Comment by teengineer** [comment]
i have internet connection, yes probably i need a VPN, so what can i do to access?

**Comment by SEU-zhc** [comment]
Idk, but I am pretty sure you can access it from Germany or US. baidu might be blocked by your IPS.
